import { test, expect } from '@playwright/test';

test('test Registrado WPC', async ({ page }) => {
  await page.goto('https://staging2.salcobrandonline.cl/login');
  await page.getByText('E-MailContraseña¿Olvidaste la').click();
  await page.getByPlaceholder('Ej: constanza@mail.com').click();
  await page.getByPlaceholder('Ej: constanza@mail.com').fill('rbenavides@sb.cl');
  await page.getByPlaceholder('Ej: constanza@mail.com').press('Tab');
  await page.locator('#spree_user_password').press('CapsLock');
  await page.locator('#spree_user_password').fill('X');
  await page.locator('#spree_user_password').press('CapsLock');
  await page.locator('#spree_user_password').fill('Xeneizes42');
  await page.goto('https://staging2.salcobrandonline.cl/?m_cod=2');
  await page.goto('https://staging2.salcobrandonline.cl/?');
  await page.getByRole('button', { name: 'Mantener ubicación' }).click();
  await page.getByPlaceholder('¿Qué estás buscando?').click();
  await page.getByPlaceholder('¿Qué estás buscando?').fill('paracetamol');
  await page.getByRole('link', { name: 'Principio Activo: Paracetamol' }).nth(1).click();
  await page.getByRole('button', { name: 'Añadir al carro' }).click();
  await page.getByText('Ir a pagar').click();
  await page.getByRole('link', { name: 'Ir a Pagar' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByLabel('DESPACHO AL DIA SIGUIENTE (LOCALES)$').check();
  await page.getByRole('button', { name: 'Continuar a medios de pago' }).click();
  await page.getByRole('button', { name: 'WebPay method Redcompra /' }).click();
  await page.getByRole('button', { name: 'WebPay method Redcompra /' }).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Realizar pago' }).click();
  await page.goto('https://staging2.salcobrandonline.cl/webpay_ws_mall?action=update&controller=spree%2Fapi%2Fv2%2Fcheckouts');
  await page.goto('https://webpay3gint.transbank.cl/webpayserver/init_transaction.cgi');
  await page.goto('https://webpay3gint.transbank.cl/webpayserver/dist/index.html');
  await page.goto('https://webpay3gint.transbank.cl/webpayserver/dist/#/');
  await page.getByRole('button', { name: 'Crédito' }).click();
  await page.getByPlaceholder('XXXX XXXX XXXX XXXX').click();
  await page.getByPlaceholder('XXXX XXXX XXXX XXXX').fill('4051 8856 0044 6623');
  await page.getByPlaceholder('MM/AA').click();
  await page.getByPlaceholder('MM/AA').fill('07/10');
  await page.getByPlaceholder('MM/AA').press('Tab');
  await page.getByPlaceholder('・・・').fill('123');
  await page.getByPlaceholder('・・・').press('Tab');
  await page.getByRole('button', { name: 'Sin Cuotas' }).press('Tab');
  await page.getByRole('button', { name: 'Pagar $' }).click();
  await page.locator('#rutClient').click();
  await page.locator('#rutClient').fill('111111111');
  await page.locator('#rutClient').press('Tab');
  await page.locator('#passwordClient').fill('123');
  await page.locator('#passwordClient').press('Tab');
  await page.getByRole('button', { name: 'Aceptar' }).press('Enter');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.goto('https://staging2.salcobrandonline.cl/webpay_ws_mall/confirmation');
  await page.goto('https://webpay3gint.transbank.cl/webpayserver/voucher.cgi');
  await page.getByRole('link', { name: 'Volver a la tienda' }).click();
});